# Program generates random numbers 
first_hash = {}
first_hash[:random_numbers] = []
first_hash[:user_input] = []
second_hash = Hash.new({"random_numbers" => 0, "user_input" => 0})

5.times do
  rand_number = rand(12..21)
  first_hash[:random_numbers].push(rand_number)
end
#print v[:random_numbers]

puts "Enter five positive integers between 12 and 21."
5.times do |count|
  puts "What's number #{count+1} "
  user_number = gets.chomp.to_i
  first_hash[:user_input].push(user_number)
end

for i in 12..21
  second_hash[i] = {
    "random_numbers" => first_hash[:random_numbers].count(i),
    "user_input" => first_hash[:user_input].count(i)
  }
end

3.times do
  puts "\r\nGive me a number you want information about: "
  info_number = gets.chomp.to_i
  #the count of times the number was generated by the program
  first_rand_count = first_hash[:random_numbers].count(info_number)
  first_user_count = first_hash[:user_input].count(info_number)
  second_rand_count = second_hash[info_number]["random_numbers"]
  second_user_count = second_hash[info_number]["user_numbers"]

  puts "Using only the first hash"
  if first_rand_count == 0
    puts " The number, #{info_number}, did not show in the randomly generated numbers."
  else
    puts " The number, #{info_number}, shows up #{first_rand_count} times(s) in the randomly generated numbers."
  end
  if first_user_count == 0
    puts " The number, #{info_number}, was not provided by the user earlier."
  else
    puts " The number, #{info_number}, was provided #{first_user_count} times(s) by the user earlier."
  end

  #keys in this hash are the numbers, either entered by the user or generated randomly by the program
  puts "Using only the second hash"
  if second_rand_count == 0
    puts " The number, #{info_number}, did not show in the randomly generated numbers."
  else
    puts " The number, #{info_number}, shows up #{second_rand_count} times(s) in the randomly generated numbers."
  end
#the count of times the number was provided earlier by the user
  if second_user_count == 0
    puts " The number, #{info_number}, was not provided by the user earlier."
  else
    puts " The number, #{info_number}, was provided #{second_user_count} times(s) by the user earlier."
  end
end

